
GET http://localhost:8080/logentries HTTP/1.1

###

POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###

POST http://localhost:8080/logentries HTTP/1.1
Content-Type: application/json

{}

###

POST http://localhost:8080/logentries HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjYWxvcmllLXRyYWNrZXIiLCJzdWIiOiJhZG1pbiIsImF1dGhvcml0aWVzIjoiUk9MRV9BRE1JTiIsImV4cCI6MTYwNTE2MDAzOX0.Uh2YP5OoaSdgXUsvHU0DearGcYKpVPkIkhlt0eWPiDg

{}

###

POST http://localhost:8080/refresh_token HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjYWxvcmllLXRyYWNrZXIiLCJzdWIiOiJhZG1pbiIsImF1dGhvcml0aWVzIjoiUk9MRV9BRE1JTiIsImV4cCI6MTYwNTE2MDAxNX0.lsQsKXUBDts-w8YhPWmdQ_mmTmERNMXyAIWBVPYGLP8
